In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\mailv\Desktop\projects\infosys\climatescope\data\GlobalWeatherRepository.csv")
print(df.head())
print(df.info())

       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch      last_updated  temperature_celsius  \
0          1715849100  2024-05-16 13:15                 26.6
1          1715849100  2024-05-16 10:45                 19.0
2          1715849100  2024-05-16 09:45                 23.0
3          1715849100  2024-05-16 10:45                  6.3
4          1715849100  2024-05-16 09:45                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                    79.8  Partly Cloudy  ...                8.4
1                    66.2  Partly cloudy  ...                1.1
2                    73.4          Sunny  ...               10.4
3                    43.3  Light drizzle  ...                0.7
4                    78.8  Partly cloudy  ...              183.4

   air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0              26.6                         1                          1
1               2.0                         1                          1
2              18.4                         1                          1
3               0.9                         1                          1
4             262.3                         5                         10

    sunrise    sunset  moonrise   moonset      moon_phase  moon_illumination
0  04:50 AM  06:50 PM  12:12 PM  01:11 AM  Waxing Gibbous                 55
1  05:21 AM  07:54 PM  12:58 PM  02:14 AM  Waxing Gibbous                 55
2  05:40 AM  07:50 PM  01:15 PM  02:14 AM  Waxing Gibbous                 55
3  06:31 AM  09:11 PM  02:12 PM  03:31 AM  Waxing Gibbous                 55
4  06:12 AM  05:55 PM  01:17 PM  12:38 AM  Waxing Gibbous                 55

[5 rows x 41 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124331 entries, 0 to 124330
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       124331 non-null  object
 1   location_name                 124331 non-null  object
 2   latitude                      124331 non-null  float64
 3   longitude                     124331 non-null  float64
 4   timezone                      124331 non-null  object
 5   last_updated_epoch            124331 non-null  int64
 6   last_updated                  124331 non-null  object
 7   temperature_celsius           124331 non-null  float64
 8   temperature_fahrenheit        124331 non-null  float64
 9   condition_text                124331 non-null  object
 10  wind_mph                      124331 non-null  float64
 11  wind_kph                      124331 non-null  float64
 12  wind_degree                   124331 non-null  int64
 13  wind_direction                124331 non-null  object
 14  pressure_mb                   124331 non-null  float64
 15  pressure_in                   124331 non-null  float64
 16  precip_mm                     124331 non-null  float64
 17  precip_in                     124331 non-null  float64
 18  humidity                      124331 non-null  int64
 19  cloud                         124331 non-null  int64
 20  feels_like_celsius            124331 non-null  float64
 21  feels_like_fahrenheit         124331 non-null  float64
 22  visibility_km                 124331 non-null  float64
 23  visibility_miles              124331 non-null  float64
 24  uv_index                      124331 non-null  float64
 25  gust_mph                      124331 non-null  float64
 26  gust_kph                      124331 non-null  float64
 27  air_quality_Carbon_Monoxide   124331 non-null  float64
 28  air_quality_Ozone             124331 non-null  float64
 29  air_quality_Nitrogen_dioxide  124331 non-null  float64
 30  air_quality_Sulphur_dioxide   124331 non-null  float64
 31  air_quality_PM2.5             124331 non-null  float64
 32  air_quality_PM10              124331 non-null  float64
 33  air_quality_us-epa-index      124331 non-null  int64
 34  air_quality_gb-defra-index    124331 non-null  int64
 35  sunrise                       124331 non-null  object
 36  sunset                        124331 non-null  object
 37  moonrise                      124331 non-null  object
 38  moonset                       124331 non-null  object
 39  moon_phase                    124331 non-null  object
 40  moon_illumination             124331 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 38.9+ MB
None

In [2]:
df.shape

(124331, 41)

In [3]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124331 entries, 0 to 124330
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       124331 non-null  object
 1   location_name                 124331 non-null  object
 2   latitude                      124331 non-null  float64
 3   longitude                     124331 non-null  float64
 4   timezone                      124331 non-null  object
 5   last_updated_epoch            124331 non-null  int64
 6   last_updated                  124331 non-null  object
 7   temperature_celsius           124331 non-null  float64
 8   temperature_fahrenheit        124331 non-null  float64
 9   condition_text                124331 non-null  object
 10  wind_mph                      124331 non-null  float64
 11  wind_kph                      124331 non-null  float64
 12  wind_degree                   124331 non-null  int64
 13  wind_direction                124331 non-null  object
 14  pressure_mb                   124331 non-null  float64
 15  pressure_in                   124331 non-null  float64
 16  precip_mm                     124331 non-null  float64
 17  precip_in                     124331 non-null  float64
 18  humidity                      124331 non-null  int64
 19  cloud                         124331 non-null  int64
 20  feels_like_celsius            124331 non-null  float64
 21  feels_like_fahrenheit         124331 non-null  float64
 22  visibility_km                 124331 non-null  float64
 23  visibility_miles              124331 non-null  float64
 24  uv_index                      124331 non-null  float64
 25  gust_mph                      124331 non-null  float64
 26  gust_kph                      124331 non-null  float64
 27  air_quality_Carbon_Monoxide   124331 non-null  float64
 28  air_quality_Ozone             124331 non-null  float64
 29  air_quality_Nitrogen_dioxide  124331 non-null  float64
 30  air_quality_Sulphur_dioxide   124331 non-null  float64
 31  air_quality_PM2.5             124331 non-null  float64
 32  air_quality_PM10              124331 non-null  float64
 33  air_quality_us-epa-index      124331 non-null  int64
 34  air_quality_gb-defra-index    124331 non-null  int64
 35  sunrise                       124331 non-null  object
 36  sunset                        124331 non-null  object
 37  moonrise                      124331 non-null  object
 38  moonset                       124331 non-null  object
 39  moon_phase                    124331 non-null  object
 40  moon_illumination             124331 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 38.9+ MB

In [5]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,124331.000000,124331.000000,1.243310e+05,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,...,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000
mean,19.193390,21.991917,1.743514e+09,21.624684,70.926181,8.070670,12.992079,169.239739,1014.058264,29.944486,...,18.310676,477.250281,58.969373,15.268437,10.692021,24.612718,49.238644,1.710491,2.635095,49.771650
std,24.426474,65.792473,1.595964e+07,9.573227,17.231665,7.377082,11.869220,103.438202,10.625605,0.313735,...,14.013010,783.608828,31.153252,24.307401,37.023338,37.882984,152.008615,0.950805,2.472790,34.993211
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729761e+09,16.300000,61.300000,4.000000,6.500000,80.000000,1010.000000,29.830000,...,10.400000,212.000000,39.000000,1.650000,1.050000,7.100000,10.050000,1.000000,1.000000,15.000000
50%,17.250000,23.240000,1.743500e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,29.930000,...,15.500000,303.400000,56.000000,5.450000,2.450000,14.250000,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.757319e+09,28.100000,82.600000,11.000000,17.600000,256.000000,1018.000000,30.060000,...,24.300000,473.600000,75.000000,17.760000,8.650000,28.120000,42.180000,2.000000,3.000000,84.000000
max,64.150000,179.220000,1.771138e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [6]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [7]:
#removing columns that are in the same just in different units(e.g. temperature in Celsius and Fahrenheit)
columns_to_drop = [
    "temperature_fahrenheit",
    "wind_mph",
    "pressure_in",
    "precip_in",
    "visibility_miles",
    "gust_mph",
    "feels_like_fahrenheit"
]

df = df.drop(columns=columns_to_drop)

In [8]:
#converting to date format
df["last_updated"] = pd.to_datetime(df["last_updated"])
df["year"] = df["last_updated"].dt.year
df["month"] = df["last_updated"].dt.month
df["day"] = df["last_updated"].dt.day

In [9]:
#standardizing column names
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
      .str.replace("-", "_")
      .str.replace(".", "", regex=False)
)

In [10]:
df.describe()

,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,...,air_quality_nitrogen_dioxide,air_quality_sulphur_dioxide,air_quality_pm25,air_quality_pm10,air_quality_us_epa_index,air_quality_gb_defra_index,moon_illumination,year,month,day
count,124331.000000,124331.000000,1.243310e+05,124331,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,...,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000,124331.000000
mean,19.193390,21.991917,1.743514e+09,2025-04-01 15:41:18.175998208,21.624684,12.992079,169.239739,1014.058264,0.136917,66.121265,...,15.268437,10.692021,24.612718,49.238644,1.710491,2.635095,49.771650,2024.712807,6.950310,15.749821
min,-41.300000,-175.200000,1.715849e+09,2024-05-16 01:45:00,-29.800000,3.600000,1.000000,947.000000,0.000000,2.000000,...,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000,2024.000000,1.000000,1.000000
25%,3.750000,-6.836100,1.729761e+09,2024-10-24 07:15:00,16.300000,6.500000,80.000000,1010.000000,0.000000,50.000000,...,1.650000,1.050000,7.100000,10.050000,1.000000,1.000000,15.000000,2024.000000,4.000000,8.000000
50%,17.250000,23.240000,1.743500e+09,2025-04-01 22:30:00,24.100000,11.200000,162.000000,1014.000000,0.000000,71.000000,...,5.450000,2.450000,14.250000,20.350000,1.000000,2.000000,50.000000,2025.000000,7.000000,16.000000
75%,40.400000,50.580000,1.757319e+09,2025-09-08 10:15:00,28.100000,17.600000,256.000000,1018.000000,0.030000,85.000000,...,17.760000,8.650000,28.120000,42.180000,2.000000,3.000000,84.000000,2025.000000,10.000000,23.000000
max,64.150000,179.220000,1.771138e+09,2026-02-15 19:45:00,49.200000,2963.200000,360.000000,3006.000000,42.240000,100.000000,...,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000,2026.000000,12.000000,31.000000
std,24.426474,65.792473,1.595964e+07,NaN,9.573227,11.869220,103.438202,10.625605,0.571760,24.020760,...,24.307401,37.023338,37.882984,152.008615,0.950805,2.472790,34.993211,0.587931,3.462159,8.830002

In [11]:
#defining seasons
def get_season(row):
    month = row["month"]
    lat = row["latitude"]
    
    # Northern Hemisphere
    if lat >= 0:
        if month in [12,1,2]:
            return "Winter"
        elif month in [3,4,5]:
            return "Spring"
        elif month in [6,7,8]:
            return "Summer"
        else:
            return "Autumn"
    
    # Southern Hemisphere (reverse)
    else:
        if month in [12,1,2]:
            return "Summer"
        elif month in [3,4,5]:
            return "Autumn"
        elif month in [6,7,8]:
            return "Winter"
        else:
            return "Spring"

df["season"] = df.apply(get_season, axis=1)

In [12]:
#checking for outliers
print("Temperature (°C):")
print("Min:", df["temperature_celsius"].min())
print("Max:", df["temperature_celsius"].max())
print()

print("Humidity (%):")
print("Min:", df["humidity"].min())
print("Max:", df["humidity"].max())
print()

print("UV Index:")
print("Min:", df["uv_index"].min())
print("Max:", df["uv_index"].max())
print()

print("Precipitation (mm):")
print("Min:", df["precip_mm"].min())
print("Max:", df["precip_mm"].max())

Temperature (°C):
Min: -29.8
Max: 49.2

Humidity (%):
Min: 2
Max: 100

UV Index:
Min: 0.0
Max: 16.3

Precipitation (mm):
Min: 0.0
Max: 42.24

In [13]:
#dataset coverage
print("Start date:", df["last_updated"].min())
print("End date:", df["last_updated"].max())
print("Unique days:", df["last_updated"].dt.date.nunique())

Start date: 2024-05-16 01:45:00
End date: 2026-02-15 19:45:00
Unique days: 640

In [14]:
import pyarrow
import fastparquet
df.to_csv("cleaned_weather.csv", index=False)
df.to_parquet("cleaned_weather.parquet", index=False)

In [15]:
monthly_summary = (
    df.groupby(["country", "year", "month"])
      .agg({
          "temperature_celsius": "mean",
          "humidity": "mean",
          "precip_mm": "sum",
          "wind_kph": "mean"
      })
      .reset_index()
)

monthly_summary.to_parquet("monthly_summary.parquet", index=False)